#ifndef SCOPELIFECORE_GLOBAL_H
#define SCOPELIFECORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCOPELIFECORE_LIBRARY)
#  define SCOPELIFECORE_EXPORT Q_DECL_EXPORT
#else
#  define SCOPELIFECORE_EXPORT Q_DECL_IMPORT
#endif


#if defined(MEDIALIBRARYCONTEXT_LIBRARY)
#  define MEDIALIBRARYCONTEXTE_EXPORT Q_DECL_EXPORT
#else
#  define MEDIALIBRARYCONTEXT_EXPORT Q_DECL_IMPORT
#endif


#if defined(SESSION_LIBRARY)
#  define SESSION_EXPORT Q_DECL_EXPORT
#else
#  define SESSION_EXPORT Q_DECL_IMPORT
#endif

#if defined(JOBQUEUE_LIBRARY)
#  define JOBQUEUE_EXPORT Q_DECL_EXPORT
#else
#  define JOBQUEUE_EXPORT Q_DECL_IMPORT
#endif


#endif // SCOPELIFECORE_GLOBAL_H
