#ifndef SCOPELIFECORE_GLOBAL_H
#define SCOPELIFECORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCOPELIFECORE_LIBRARY)
#  define SCOPELIFECORE_EXPORT Q_DECL_EXPORT
#else
#  define SCOPELIFECORE_EXPORT Q_DECL_IMPORT
#endif

#endif // SCOPELIFECORE_GLOBAL_H
